-- Your SQL goes here

CREATE TABLE employee (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  first_name VARCHAR(255) NOT NULL,
  last_name VARCHAR(255) NOT NULL,
  phone VARCHAR(255),
  address VARCHAR(255) NOT NULL,
  start_date TIMESTAMP,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
